{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-app.fullname" . }}-mysql
  namespace: {{ include "library-app.namespace" . }}
  labels:
    {{- include "library-app.labels" . | nindent 4 }}
    component: mysql
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: 3306
    protocol: TCP
  selector:
    {{- include "library-app.selectorLabels" . | nindent 4 }}
    component: mysql
{{- end }}