# FROM node:20-alpine

# RUN apk add --no-cache git python3 make g++

# WORKDIR /app_parent

# COPY package.json package-lock.json ./
# RUN npm ci

# RUN mkdir -p app
# WORKDIR /app_parent/app

# COPY public/ ./public/
# COPY src/ ./src/
# COPY tsconfig.json ./
# COPY package.json ./

# ENV NODE_PATH=/app_parent/node_modules
# ENV PATH=/app_parent/node_modules/.bin:$PATH
# ENV SKIP_PREFLIGHT_CHECK=true

# CMD ["sh", "-c", "NODE_PATH=/app_parent/node_modules WDS_SOCKET_HOST=localhost WDS_SOCKET_PORT=5500 npm run dev"]

FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# Для разработки оставляем dev зависимости
CMD ["npm", "run", "dev"]