services:
  db_lib:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lib_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: always

  django:
    build:
      context: ./back
      dockerfile: Dockerfile.prod
    volumes:
      - ./back:/app
    # ports:
    #   - "8000:8000"
    environment:
      DATABASE_HOST: db_lib
      DATABASE_NAME: lib_db
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DJANGO_DEBUG: "false"
    depends_on:
      db_lib:
        condition: service_healthy
    restart: always

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - nextjs_build:/app/.next
    depends_on:
      - django
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - "5500:80"
    volumes:
      - ./nginx/conf.d/default.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - nextjs_build:/usr/share/nginx/html/_next:ro
    depends_on:
      - django
      - nextjs
    restart: always

volumes:
  db_data:
  nextjs_build:
