# Generated by Django 5.2.4 on 2025-07-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_author_publisher_remove_book_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="genres",
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="api.publisher",
            ),
        ),
    ]
