# Generated by Django 5.2.4 on 2025-07-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_book_genres_alter_book_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(
                default="Unknown Author", max_length=255, unique=True
            ),
        ),
    ]
