# Generated by Django 5.2.4 on 2025-08-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_book_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorNGram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngram', models.CharField(db_index=True, max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngrams', to='api.author')),
            ],
            options={
                'indexes': [models.Index(fields=['ngram'], name='api_authorn_ngram_5baec2_idx'), models.Index(fields=['author', 'ngram'], name='api_authorn_author__484662_idx')],
                'unique_together': {('author', 'ngram')},
            },
        ),
        migrations.CreateModel(
            name='AuthorTrigram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigram', models.CharField(db_index=True, max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigrams', to='api.author')),
            ],
            options={
                'indexes': [models.Index(fields=['trigram'], name='api_authort_trigram_1d530d_idx'), models.Index(fields=['author', 'trigram'], name='api_authort_author__89eeff_idx')],
                'unique_together': {('author', 'trigram')},
            },
        ),
    ]
