# Generated by Django 5.2.5 on 2025-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_book_book_image_book_description_book_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
