{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "library-app.fullname" . }}-nginx
  labels:
    {{- include "library-app.labels" . | nindent 4 }}
    component: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      {{- include "library-app.selectorLabels" . | nindent 6 }}
      component: nginx
  template:
    metadata:
      labels:
        {{- include "library-app.selectorLabels" . | nindent 8 }}
        component: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}
        ports:
        - containerPort: 5500
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
        resources:
          {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "library-app.fullname" . }}-nginx-config
{{- end }}